### ISSUE TITLE
Blender segfaults when adding cabinets to a kitchen

### ISSUE THREAD

**Issue by bartfailt** [s-leger/archipack#308] opened 2022-03-12 08:51 UTC
Archipack version: 2.4.0

Blender version: 2.93, 3.0.1, 3.1

Os version: Manjaro latest

Description of the issue:

I was able to reproduce the issue with Blender 2.93 (from snap store), 3.0.1 installed from Manjaro repositories and 3.1 installed from flatpak.

Create a kitchen, and try adding cabinets to it. In a new file it crashes when trying to add the 5th cabinet, but sometimes if tails right after trying to add the second.

Screenshot when reproducing:
![Screenshot from 2022-03-12 09-47-13](https://user-images.githubusercontent.com/49832897/158011001-47f682e7-62cd-4f40-a0ca-c0d24d77b73f.png)

Coredump info:
[blender-archipack-kitchen-coredump-info.txt](https://github.com/s-leger/archipack/files/8237323/blender-archipack-kitchen-coredump-info.txt)

**Comment by bartfailt** [comment] 2022-03-12 08:57
The crash only happens when I start with either of the three single cabinet preset (Euronorm, Ikea, Swissnorm). More complex presets can be extended, even adding 70 extra cabinets works

**Comment by s-leger** [comment] 2022-07-29 09:38
Confirmed, i'm able to repro the error. 
Looks like it is at least partially related to custom objects pointers.

**Comment by s-leger** [comment] 2022-10-09 17:57
Fixed in 2.5.1

**Closed as completed by s-leger** 2022-10-09 17:57 UTC
