### ISSUE TITLE
Windows are added with empty panel

### ISSUE THREAD

**Issue by abecido** [s-leger/archipack#136] opened 2019-07-25 18:35 UTC
Archipack version: 2.79b

Blender version: 2.79b

Os version: debian Buster 4.13

Description of the issue: new windows are added with empty panel. Panels are created but with no dimension. That was working well yesterday.

![Screenshot_20190725_203112](https://user-images.githubusercontent.com/14327707/61899396-a3e23700-af1b-11e9-86d1-6d25e8735cf4.png)
![Screenshot_20190725_203237](https://user-images.githubusercontent.com/14327707/61899402-a80e5480-af1b-11e9-844e-251c5016bb71.png)

**Comment by s-leger** [comment] 2019-07-25 18:41
Looks odd, as nothing changed in 2.79b and archipack since like 6 month now.
Any error in the console ?
Could you also tell version of archipack (in addon prefs) ?

**Comment by abecido** [comment] 2019-07-25 19:54
archipack version : 1.2.8

Yes, there is message !  : 

```
Archipack: unable to add material DEFAULT for window
Warning: Material DEFAULT for window not found
Error: Traceback (most recent call last):
  File "/usr/share/blender/scripts/addons/archipack/archipack_window.py", line 2182, in execute
    o = self.create(context)
  File "/usr/share/blender/scripts/addons/archipack/archipack_window.py", line 2169, in create
    m.material = self.material
TypeError: bpy_struct: item.attr = val: enum "" not found in ()

location: /usr/share/blender/scripts/modules/bpy/ops.py:189
```

**Comment by s-leger** [comment] 2019-07-25 20:03
Duplicate of #133 
Will continue discussion there.

**Closed as completed by s-leger** 2019-07-25 20:03 UTC
