### ISSUE TITLE
First windows/doors not making boolean

### ISSUE THREAD

**Issue by Aqualung10** [s-leger/archipack#94] opened 2019-01-29 11:57 UTC
Hello all,

I'm having a little problem with this addon. After I create a wall, the first window or door never creates the boolean, but the next ones create the booleans just fine. Is it a bug or am I doing something wrong?

Blender version:
2.79.6

Version:
Archipack 1.4.1

![bug1](https://user-images.githubusercontent.com/47143802/51906834-07e8d000-23bd-11e9-851e-f823cde010d1.png)

**Comment by s-leger** [comment] 2019-01-29 17:40
Confirmed,
In the meantime, select the wall and use "AutoBoolean" to fix missing booleans.

**Comment by rrmelcer** [comment] 2019-02-12 10:51
On Manjaro Linux with Blender 2.79.6 and Archipack 1.2.8 the "AutoBoolian" don't work, become a Error message.

**Comment by s-leger** [comment] 2019-02-12 18:19
You have to select a wall before using AutoBoolean, also keep in mind that 1.2.8 version was initially done for first 2.79 release, so probably 2.79.6 break something in the between.

**Comment by rrmelcer** [comment] 2019-02-15 08:05
Please excuse my persistence but it seems to be a bug in the script, I just want to provide this as input so this great project can continue to grow.
I get the following error message even if I selected the wall before:
![grafik](https://user-images.githubusercontent.com/8833269/52842902-ccf6d400-3100-11e9-9847-2e044c91084d.png)

**Comment by s-leger** [comment] 2019-02-15 16:39
In Blender 2.79.6 there is no more support for carve mode in booleans. I cant edit the 1.2.8 version as it does work with 2.79 official.
Download a recent archipack for 2.79 from https://blender-archipack.org/

**Comment by s-leger** [comment] 2019-04-07 08:05
Should be fixed now.

**Closed by s-leger** 2019-04-07 08:05 UTC
Labels: bug
