### ISSUE TITLE
problems to install Archipack addon

### ISSUE THREAD

**Issue by tartyto** [s-leger/archipack#158] opened 2019-12-20 14:01 UTC
Archipack version: 1.2.83

Blender version: 2.82

Os version: linux xubuntu 18.04

Description of the issue: I don't now what is happening but i can't install the addon

![Captura de pantalla_2019-12-20_14-58-27](https://user-images.githubusercontent.com/49335028/71259653-3656fd00-2339-11ea-9bef-722de47e3206.png)

> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 16, in <module>
>     from . import multiarray
> ImportError: cannot import name 'multiarray' from 'numpy.core' (/usr/lib/python3/dist-packages/numpy/core/__init__.py)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/share/blender/2.82/scripts/modules/addon_utils.py", line 351, in enable
>     mod = __import__(module_name)
>   File "/usr/share/blender/2.82/scripts/addons/archipack/__init__.py", line 69, in <module>
>     from . import archipack_manipulator
>   File "/usr/share/blender/2.82/scripts/addons/archipack/archipack_manipulator.py", line 43, in <module>
>     from .archipack_gl import (
>   File "/usr/share/blender/2.82/scripts/addons/archipack/archipack_gl.py", line 32, in <module>
>     import numpy as np
>   File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
>     from . import add_newdocs
>   File "/usr/lib/python3/dist-packages/numpy/add_newdocs.py", line 13, in <module>
>     from numpy.lib import add_newdoc
>   File "/usr/lib/python3/dist-packages/numpy/lib/__init__.py", line 8, in <module>
>     from .type_check import *
>   File "/usr/lib/python3/dist-packages/numpy/lib/type_check.py", line 11, in <module>
>     import numpy.core.numeric as _nx
>   File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 26, in <module>
>     raise ImportError(msg)
> ImportError: 
> Importing the multiarray numpy extension module failed.  Most
> likely you are trying to import a failed build of numpy.
> If you're working with a numpy git repo, try `git clean -xdf` (removes all
> files not under version control).  Otherwise reinstall numpy.
> 
> Original error was: cannot import name 'multiarray' from 'numpy.core' (/usr/lib/python3/dist-packages/numpy/core/__init__.py)
> 

Please Help Me

**Comment by s-leger** [comment] 2019-12-20 22:34
duplicate of #63 
this is a known issue with non standard / incomplete blender setup. Either setup numpy by hand or download and setup from official blender.org.

**Closed as completed by s-leger** 2019-12-20 22:34 UTC
